[workspace]
resolver = "2"
members = [
  "tikal",
  "tikal-macros",
  "tikal-mariadb",
  "tikal-postgres",
  "tikal-sqlite",
]
[workspace.package]
version = "0.1.3"
edition = "2024"
description = "A Rust ORM library for building database-driven applications"
authors = ["Hector3269 <danielramirezr27@gmail.com>"]
repository = "https://github.com/Hector3269/Tikal.git"
readme = "README.md"
license-file = "LICENSE"
